// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCH6sKa0kS6GQftZh_hS-s35R82LC7YEOU',
    appId: '1:621719543191:android:b3dae7f1cdafd48c03b8d2',
    messagingSenderId: '621719543191',
    projectId: 'bnote-51adf',
    storageBucket: 'bnote-51adf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3sOgWuxnHklnoWmYYknCihjruEqUGxJc',
    appId: '1:621719543191:ios:bd981335346518b903b8d2',
    messagingSenderId: '621719543191',
    projectId: 'bnote-51adf',
    storageBucket: 'bnote-51adf.appspot.com',
    iosClientId: '621719543191-kdcngm569shuuskc49ps1iodatq40imf.apps.googleusercontent.com',
    iosBundleId: 'com.pleaperf.bnote',
  );
}
